name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21.0.2'
        distribution: 'temurin'
      
    #- name: Build Docker Image
      #run:  docker build -t rizlaman401/spring-petclinic:latest .

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Push Docker Image to Docker Hub
    #- name: Push Docker Image to Docker Hub
      #run: docker push rizlaman401/spring-petclinic:latest

    # Log in to Amazon ECR
    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    # Tag Docker Image for ECR
    - name: Tag Docker Image for ECR
      run: docker tag myapp:latest 402319074183.dkr.ecr.us-east-1.amazonaws.com/petclinic:latest

    # Push Docker Image to ECR
    - name: Push Docker Image to ECR
      run: docker push 402319074183.dkr.ecr.us-east-1.amazonaws.com/petclinic:latest

    - name: Fill in the new image ID in the ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        input: task-definition.json
        image: 402319074183.dkr.ecr.us-east-1.amazonaws.com/petclinic:latest

    - name: Deploy image to ECS Service
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        service: myapp-service
        cluster: ibi_pet_clinic
        task-definition: ${{ steps.task-def.outputs.task-definition }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: packaged-artifacts
        path: target/*.jar
