name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21.0.2'
        distribution: 'temurin' 
        
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2
          
    - name: Build with Maven
      run: ./mvnw clean install

    - name: Run tests
      run: ./mvnw test

    - name: Package
      run: ./mvnw clean package

    - name: Build Docker Image
      run: docker build -t rizlaman401/spring-petclinic:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run: docker push rizlaman401/spring-petclinic:latest
      
    - name: Install Heroku CLI
      run: curl https://cli-assets.heroku.com/install.sh | sh
    
    - name: Heroku Login
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku auth:token
      
    - name: Authenticate Heroku CLI
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        echo $HEROKU_API_KEY | heroku auth:token
        
    - name: Login to Heroku Container Registry
      run: heroku container:login

    - name: Tag Docker Image
      run: docker tag rizlaman401/spring-petclinic:latest registry.heroku.com/pet-clinic/web

    - name: Push Docker Image to Heroku
      run: docker push registry.heroku.com/pet-clinic/web

    - name: Release Docker Image on Heroku
      run: heroku container:release web --app pet-clinic

        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: packaged-artifacts
        path: target/packaged-artifacts.jar
