name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21.0.2'
        distribution: 'temurin' 
        
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2
          
    #- name: Build with Maven
      #run: ./mvnw clean install

    #- name: Run tests
      #run: ./mvnw test

    #- name: Package
      #run: ./mvnw clean package

    #- name: Build Docker Image
      #run: docker build -t rizlaman401/spring-petclinic:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    #- name: Push Docker Image
      #run: docker push rizlaman401/spring-petclinic:latest

    - name: Update ECS Service
      run: aws ecs update-service --cluster test_case_ibi_k_pet_clinic --service Petclinic --force-new-deployment --debug
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    #- name: Upload Artifacts
      #uses: actions/upload-artifact@v2
      #with:
        #name: packaged-artifacts
        #path: target/packaged-artifacts.jar
